---
 - hosts: "{{ group }}"
   become : true
   
   tasks:

   - name: Update nodejs package
     shell: curl -fsSL https://deb.nodesource.com/setup_15.x | sudo -E bash -

   - name: Install nodejs
     apt:
       name: nodejs
       state: present

   - name: Npm initialization
     shell: npm init -y
     args:
       chdir: '{{ deploy_directory }}/'

   - name: Install node dependencies
     shell: npm install
     args:
       chdir: '{{ deploy_directory }}/'

   - name: Get public IP
     community.general.ipify_facts:

   - name: Create environment variables file
     copy:
       dest: "{{ deploy_directory }}/.env"
       content: |
         PORT={{ http_port }}
         HOST='0.0.0.0'
         HOST_URL=http://{{ public_ip }}:{{ http_port }}
         COOKIE_ENCRYPT_PWD=superAwesomePasswordStringThatIsAtLeast32CharactersLong!
         NODE_ENV=development
         PGHOST={{ pg_host }}
         PGUSERNAME={{ pg_username }}
         PGDATABASE={{ pg_database }}
         PGPASSWORD={{ pg_password }}
         PGPORT=5432
         OKTA_ORG_URL={{ okta_org_url }}
         OKTA_CLIENT_ID={{ okta_client_id }}
         OKTA_CLIENT_SECRET={{ okta_client_secret }}
   - name: Database initialization
     shell: npm run initdb
     async: 30
     poll: 0
     args:
       chdir: '{{ deploy_directory }}/'
       
   - name: install dependencies
     become: yes
     command: "npm install {{ item }}"
     args:
       chdir: /home/{{ USERNAME }}/bootcamp-app
     with_items:
        - '@hapi/hapi@19'
        - '@hapi/bell@12'
        - '@hapi/boom@9'
        - '@hapi/cookie@11'
        - '@hapi/inert@6'
        - '@hapi/joi@17'
        - '@hapi/vision@6'
        - 'dotenv@8'
        - 'ejs@3'
        - 'postgres@1'

   - name: Install pm2
     shell: npm install pm2 -g

   - name: Clear pm2 process
     shell: pm2 delete all
     ignore_errors: yes

   - name: Run application
     shell: pm2 start npm -- run dev && pm2 save && pm2 startup
     args:
       chdir: '{{ deploy_directory }}/'

   - name: Reboot
     reboot:
